lib/contento_web/router.ex
defmodule ContentoWeb.Router do
  use ContentoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :contento do
    plug ContentoWeb.Plug.AuthRequired
    plug :put_layout, {ContentoWeb.LayoutView, "contento.html"}
  end

  pipeline :session do
    plug :put_layout, {ContentoWeb.SessionView, "layout.html"}
  end

  pipeline :theme do
    plug ContentoWeb.Plug.Website
    plug ContentoWeb.Plug.Theme
    plug ContentoWeb.Plug.Maintenance
  end

  if Mix.env == :dev do
    scope "/debug" do
      forward "/sent_emails", Bamboo.EmailPreviewPlug
    end
  end

  scope "/c", ContentoWeb, as: :admin do
    pipe_through [:browser, :contento]

    # Account
    scope "/account" do
      get "/", AccountController, :index
      put "/", AccountController, :update
      put "/password", AccountController, :update_password
    end

    # Dashboard
    get "/", DashboardController, :index

    # Permissions
    resources "/permissions", PermissionController, except: [:edit]

    # Roles
    resources "/roles", RoleController, except: [:edit]

    # Users
    resources "/users", UserController, except: [:edit]

    # Posts
    resources "/posts", PostController, except: [:edit]

    # Pages
    resources "/pages", PageController, except: [:edit]

    # Themes
    resources "/themes", ThemeController, except: [:edit]

    # Settings
    get "/settings", SettingsController, :show
    put "/settings", SettingsController, :update
    put "/settings/theme", SettingsController, :update_theme
  end

  scope "/", ContentoWeb do
    pipe_through [:browser, :session]

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete

    get "/activate/:token", SessionController, :activate
  end

  scope "/", ContentoWeb do
    pipe_through [:browser, :theme]

    # Index
    get "/", WebsiteController, :index

    # Author
    get "/authors/:handle", WebsiteController, :show_author

    # Show Post
    get "/blog", WebsiteController, :index
    get "/blog/:slug", WebsiteController, :show_post
    
    # Show Page
    get "/:slug", WebsiteController, :show_page

    # Page or Post
    # get "/:slug", WebsiteController, :page_or_post
  end
end

lib/contento_web/templates/page/form.html.eex
<div>
  <h1 class="header">
    <div><%= gettext("Page Details") %></div>
  </h1>

  <%= form_for @changeset, @action, fn f -> %>
    <div class="form-group">
      <%= label f, :title, gettext("Title") %>
      <%= text_input f, :title, class: input_class(f, :title) %>
      <%= input_errors f, :title %>
    </div>

    <div class="form-group">
      <%= label f, :content, gettext("Content") %>
      <%= textarea f, :content, class: input_class(f, :content), rows: 15, data: [provide: "markdown", iconlibrary: "fa"] %>
      <%= input_errors f, :content %>
    </div>

    <div class="form-group">
      <%= label f, :slug, gettext("Slug") %>
      <%= text_input f, :slug, class: input_class(f, :slug) %>
      <%= input_errors f, :slug %>
    </div>

    <div class="form-group">
      <%= label f, :published, gettext("Status") %>
      <%= select f, :published, ["Published": true, "Draft": false], class: input_class(f, :published) %>
      <%= input_errors f, :published %>
    </div>

    <div class="text-right">
      <button type="submit" class="btn btn-primary">
        <%= gettext("Save") %>
      </button>
    </div>
  <% end %>
</div>

lib/contento_web/templates/page/index.html.eex
<div class="breadcrumbs">
  <a href="<%= admin_dashboard_path(@conn, :index) %>">
    <%= gettext("Contento") %>
  </a>
  <span><%= gettext("Pages") %></span>
</div>

<div class="content">
  <h1 class="header">
    <div><%= gettext("Pages") %></div>
    <div>
      <a href="<%= admin_page_path(@conn, :new) %>" class="btn btn-sm btn-primary">
        <%= gettext("New Page") %>
      </a>
    </div>
  </h1>

  <%= if info = get_flash(@conn, :info) do %>
    <%= case info do %>
      <% :created -> %>
        <div class="alert alert-success">
          <%= gettext("Page successfully created") %>
        </div>
      <% :deleted -> %>
        <div class="alert alert-success">
          <%= gettext("Page successfully deleted") %>
        </div>
    <% end %>
  <% end %>

  <%= if length(@pages) > 0 do %>
    <div class="list-group">
      <%= for page <- @pages do %>
        <a href="<%= admin_page_path(@conn, :show, page) %>" class="list-group-item">
          <strong><%= page.title %></strong> by <em><%= page.author.name %></em>
          <br />
          <span><%= website_url(@conn, :show_page, page.slug) %></span>
        </a>
      <% end %>
    </div>

    <%= render ContentoWeb.LayoutView, "pagination.html", conn: @conn, total_pages: @total_pages,
                                                          page_number: @page_number %>
  <% else %>
    <div class="alert alert-info">
      <%= gettext("No pages found...") %>
    </div>
  <% end %>
</div>

lib/contento_web/templates/page/new.html.eex
<div class="breadcrumbs">
  <a href="<%= admin_dashboard_path(@conn, :index) %>">
    <%= gettext("Contento") %>
  </a>
  <a href="<%= admin_page_path(@conn, :index) %>">
    <%= gettext("Pages") %>
  </a>
  <span><%= gettext("New") %></span>
</div>

<div class="content">
  <%= render "form.html", changeset: @changeset, action: admin_page_path(@conn, :create) %>
</div>

lib/contento_web/templates/page/show.html.eex
<div class="breadcrumbs">
  <a href="<%= admin_dashboard_path(@conn, :index) %>">
    <%= gettext("Contento") %>
  </a>
  <a href="<%= admin_page_path(@conn, :index) %>">
    <%= gettext("Pages") %>
  </a>
  <span><%= @page.title %></span>
</div>

<div class="content">
  <div class="row">
    <div class="col-md-8">
      <%= if info = get_flash(@conn, :info) do %>
        <%= case info do %>
          <% :updated -> %>
            <div class="alert alert-success">
              <%= gettext("Page successfully updated") %>
            </div>
        <% end %>
      <% end %>

      <%= render "form.html", changeset: @changeset, action: admin_page_path(@conn, :update, @page) %>
    </div>
    <div class="col-md-4">
      <h1 class="header">
        <div><%= gettext("Info") %></div>
      </h1>

      <ul class="list-group">
        <li class="list-group-item">
          <strong><%= gettext("Author") %>:</strong>
          <a href="<%= admin_user_path(@conn, :show, @page.author) %>">
            <%= @page.author.name %>
          </a>
        </li>
        <li class="list-group-item">
          <%= if published_at = @page.published_at do %>
            <strong><%= gettext("Published") %>:</strong>
            <%= timeago(published_at) %>
          <% else %>
            <em>Not Published</em>
          <% end %>
        </li>
        <li class="list-group-item">
          <strong><%= gettext("Inserted") %>:</strong>
          <%= timeago(@page.inserted_at) %>
        </li>
        <li class="list-group-item">
          <strong><%= gettext("Updated") %>:</strong>
          <%= timeago(@page.updated_at) %>
        </li>
      </ul>

      <div class="mt-3">
        <%= link gettext("Delete Page"), to: admin_page_path(@conn, :delete, @page),
                                         method: :delete, class: "text-danger",
                                         data: [confirm: gettext("Are you sure you want to delete this page?")] %>
      </div>
    </div>
  </div>
</div>