lib/contento_web/router.ex
defmodule ContentoWeb.Router do
  use ContentoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :contento do
    plug ContentoWeb.Plug.AuthRequired
    plug :put_layout, {ContentoWeb.LayoutView, "contento.html"}
  end

  pipeline :session do
    plug :put_layout, {ContentoWeb.SessionView, "layout.html"}
  end

  pipeline :theme do
    plug ContentoWeb.Plug.Website
    plug ContentoWeb.Plug.Theme
    plug ContentoWeb.Plug.Maintenance
  end

  if Mix.env == :dev do
    scope "/debug" do
      forward "/sent_emails", Bamboo.EmailPreviewPlug
    end
  end

  scope "/c", ContentoWeb, as: :admin do
    pipe_through [:browser, :contento]

    # Account
    scope "/account" do
      get "/", AccountController, :index
      put "/", AccountController, :update
      put "/password", AccountController, :update_password
    end

    # Dashboard
    get "/", DashboardController, :index

    # Permissions
    resources "/permissions", PermissionController, except: [:edit]

    # Roles
    resources "/roles", RoleController, except: [:edit]

    # Users
    resources "/users", UserController, except: [:edit]

    # Posts
    resources "/posts", PostController, except: [:edit]

    # Pages
    resources "/pages", PageController, except: [:edit]

    # Themes
    resources "/themes", ThemeController, except: [:edit]

    # Settings
    get "/settings", SettingsController, :show
    put "/settings", SettingsController, :update
    put "/settings/theme", SettingsController, :update_theme
  end

  scope "/", ContentoWeb do
    pipe_through [:browser, :session]

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete

    get "/activate/:token", SessionController, :activate
  end

  scope "/", ContentoWeb do
    pipe_through [:browser, :theme]

    # Index
    get "/", WebsiteController, :index

    # Author
    get "/authors/:handle", WebsiteController, :show_author

    # Show Post
    get "/blog", WebsiteController, :index
    get "/blog/:slug", WebsiteController, :show_post
    
    # Show Page
    get "/:slug", WebsiteController, :show_page

    # Page or Post
    # get "/:slug", WebsiteController, :page_or_post
  end
end

lib/contento_web/views/layout_view.ex
defmodule ContentoWeb.LayoutView do
  use ContentoWeb, :view
end

lib/contento_web/templates/layout/contento.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><%= page_title(@conn) %></title>

    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/contento.css") %>">
  </head>
  <body>
    <div class="wrapper">
      <div class="sidebar">
        <a href="<%= admin_dashboard_path(@conn, :index) %>" class="brand text-center">
          <img src="<%= static_path(@conn, "/images/logo.png") %>" height="48" alt="Contento's Logo" />
        </a>
        <div class="user">
          <div class="username">
            <%= current_user(@conn).name %>
          </div>
          <div class="extension">
            <div class="username">
              <%= current_user(@conn).name %>
            </div>
            <div class="nav flex-column">
              <a href="<%= admin_account_path(@conn, :index) %>" class="nav-item nav-link">
                <%= gettext("Account") %>
              </a>
              <div class="separator"></div>
              <a href="<%= session_path(@conn, :delete) %>" class="nav-item nav-link">
                <%= gettext("Logout") %>
              </a>
            </div>
          </div>
        </div>
        <div class="nav flex-column">
          <span class="nav-header"><%= gettext("Main") %></span>
          <a href="<%= website_path(@conn, :index) %>" class="nav-item nav-link" target="website">
            <span class="fa fa-globe"></span>
            <%= gettext("View Website") %>
          </a>
          <a href="<%= admin_dashboard_path(@conn, :index) %>" class="nav-item nav-link <%= active_class(@conn, admin_dashboard_path(@conn, :index)) %>">
            <span class="fa fa-dashboard"></span>
            <%= gettext("Dashboard") %>
          </a>

          <span class="nav-header"><%= gettext("Content") %></span>
          <a href="<%= admin_post_path(@conn, :index) %>" class="nav-item nav-link <%= active_class(@conn, admin_post_path(@conn, :index)) %>">
            <span class="fa fa-sticky-note"></span>
            <%= gettext("Posts") %>
          </a>
          <a href="<%= admin_page_path(@conn, :index) %>" class="nav-item nav-link <%= active_class(@conn, admin_page_path(@conn, :index)) %>">
            <span class="fa fa-file-text"></span>
            <%= gettext("Pages") %>
          </a>

          <span class="nav-header"><%= gettext("Appearance") %></span>
          <a href="<%= admin_theme_path(@conn, :index) %>" class="nav-item nav-link <%= active_class(@conn, admin_theme_path(@conn, :index)) %>">
            <span class="fa fa-paint-brush"></span>
            <%= gettext("Themes") %>
          </a>

          <span class="nav-header"><%= gettext("System") %></span>
          <a href="<%= admin_user_path(@conn, :index) %>" class="nav-item nav-link <%= active_class(@conn, admin_user_path(@conn, :index)) %>">
            <span class="fa fa-group"></span>
            <%= gettext("Users") %>
          </a>
          <a href="<%= admin_role_path(@conn, :index) %>" class="nav-item nav-link <%= active_class(@conn, admin_role_path(@conn, :index)) %>">
            <span class="fa fa-id-card"></span>
            <%= gettext("Roles") %>
          </a>
          <a href="<%= admin_permission_path(@conn, :index) %>" class="nav-item nav-link <%= active_class(@conn, admin_permission_path(@conn, :index)) %>">
            <span class="fa fa-eye"></span>
            <%= gettext("Permissions") %>
          </a>
          <a href="<%= admin_settings_path(@conn, :show) %>" class="nav-item nav-link <%= active_class(@conn, admin_settings_path(@conn, :show)) %>">
            <span class="fa fa-cog"></span>
            <%= gettext("Settings") %>
          </a>
        </div>
      </div>
      <div class="main">
        <%= @inner_content %>
      </div>
    </div>

    <script src="<%= static_path(@conn, "/js/contento.js") %>"></script>
  </body>
</html>

lib/contento_web/templates/layout/pagination.html.eex
<nav class="mt-3">
  <ul class="pagination">
    <%= if @page_number == 1 do %>
      <li class="page-item disabled">
        <a class="page-link" href="javascript:;">
          <%= gettext("Previous") %>
        </a>
      </li>
    <% else %>
      <li class="page-item">
        <a class="page-link" href="<%= admin_page_path(@conn, :index, page: @page_number - 1) %>">
          <%= gettext("Previous") %>
        </a>
      </li>
    <% end %>
    <%= for page <- 1..@total_pages do %>
      <%= if page == @page_number do %>
        <li class="page-item active">
          <a class="page-link" href="<%= admin_page_path(@conn, :index, page: page) %>">
            <%= page %>
          </a>
        </li>
      <% else %>
        <li class="page-item">
          <a class="page-link" href="<%= admin_page_path(@conn, :index, page: page) %>">
            <%= page %>
          </a>
        </li>
      <% end %>
    <% end %>
    <%= if @total_pages == @page_number do %>
      <li class="page-item disabled">
        <a class="page-link" href="javascript:;">
          <%= gettext("Next") %>
        </a>
      </li>
    <% else %>
      <li class="page-item">
        <a class="page-link" href="<%= admin_page_path(@conn, :index, page: @page_number + 1) %>">
          <%= gettext("Next") %>
        </a>
      </li>
    <% end %>
  </ul>
</nav>